"""Agregar is_active y modelos completos

Revision ID: 0d824abd8602
Revises: 6fee3d62acdf
Create Date: 2026-01-25 18:39:53.182155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d824abd8602'
down_revision = '6fee3d62acdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('marketing_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketing_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=100), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('price_promotion', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['marketing_id'], ['marketing.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('additionals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('concept', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('category_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('category_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_id', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(None, ['number_id'])

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.create_foreign_key(None, 'roles', ['rol_id'], ['id'])

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_active')
        batch_op.drop_column('rol_id')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_active')
        batch_op.drop_column('number_id')

    with op.batch_alter_table('category_services', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('category_products', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    op.drop_table('additionals')
    op.drop_table('marketing_items')
    op.drop_table('roles')
    # ### end Alembic commands ###
